import { NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import { checkGuardrails, DB_SCHEMA } from '@/lib/guardrails';
import { executeQuery } from '@/lib/db';

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

export async function POST(req: Request) {
  try {
    const { query } = await req.json();

    if (!query) {
      return NextResponse.json({ status: 'error', error: 'Query is required' }, { status: 400 });
    }

    // 1. Guardrails Check
    const guardrailCheck = checkGuardrails(query);
    if (!guardrailCheck.isValid) {
      return NextResponse.json({ 
        reason: guardrailCheck.reason,
        status: 'rejected'
      });
    }

    // 2. Gemini SQL Generation
    const sqlGenerationSystemPrompt = `You are an expert SQL generator for a brokerage database.
Your job is to translate the user\'s natural language query into a raw SQLite query.

Here is the database schema:
${DB_SCHEMA}

CRITICAL RULES:
- Return ONLY the raw SQL query, absolutely no markdown formatting, no \`\`\`sql block, no explanation.
- ONLY read operations using SELECT are allowed. NEVER use UPDATE, DELETE, DROP, INSERT, etc.
- Always use LIMIT 100 on open-ended queries unless the user asks for aggregation/counts to prevent huge returns.
- Assume all price columns/totals should be rounded appropriately.
`;

    const messageResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash', 
      contents: query,
      config: {
        systemInstruction: sqlGenerationSystemPrompt,
        temperature: 0,
        maxOutputTokens: 2000,
      }
    });

    let generatedSql = messageResponse.text?.trim() || '';
    console.log("DEBUG: messageResponse =", JSON.stringify(messageResponse, null, 2));
    if (!generatedSql) {
      return NextResponse.json({ error: 'Did not generate SQL', status: 'error' });
    }
    
    // Safety check just in case Gemini outputs Markdown
    generatedSql = generatedSql.replace(/^```sql/i, '').replace(/```$/, '').trim();

    // Secondary safety check for destructive queries generated by the LLM
    const secondCheck = checkGuardrails(generatedSql);
    if (!secondCheck.isValid) {
      return NextResponse.json({
        reason: 'Generated query violates security policies: ' + secondCheck.reason,
        status: 'rejected',
        sql: generatedSql
      });
    }

    // 3. Database Execution
    const dbResult = executeQuery(generatedSql);

    if (!dbResult.success) {
      return NextResponse.json({
         status: 'error',
         sql: generatedSql,
         error: dbResult.error
      });
    }

    const maxSummaryRows = dbResult.rows?.slice(0, 10) || [];

    // 4. Summarization
    const summarizationSystemPrompt = `You are a helpful brokerage assistant. Your task is to summarize the results of a SQL query based on the user's initial question.
Be extremely concise. Write one or two plain-English sentences maximum. Do not mention "the database" or "the SQL query returned" or provide data that contradicts the results.
If there are many rows, just mention top results or a high-level summary.`;

    const summarizationContent = `User Question: "${query}"
SQL Query Executed: "${generatedSql}"
Top 10 Rows Result:
${JSON.stringify(maxSummaryRows, null, 2)}
`;

    const summaryResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: summarizationContent,
      config: {
        systemInstruction: summarizationSystemPrompt,
        temperature: 0.2,
        maxOutputTokens: 1000,
      }
    });

    let summary = summaryResponse.text?.trim() || 'No summary generated.';

    return NextResponse.json({
      status: 'success',
      sql: generatedSql,
      results: dbResult.rows,
      summary
    });

  } catch (error) {
    console.error('API Error:', error);
    return NextResponse.json({ 
        status: 'error', 
        error: error instanceof Error ? error.message : String(error) 
    }, { status: 500 });
  }
}
